table Fact_UN_Population_Indicators
	lineageTag: 066fd461-f007-4f24-9590-c5349ad54c55

	column IndicatorId
		dataType: int64
		formatString: 0
		lineageTag: b4b04c4a-d424-402a-aebb-f67c352c657a
		summarizeBy: none
		sourceColumn: IndicatorId

		annotation SummarizationSetBy = Automatic

	column Indicator
		dataType: string
		lineageTag: 6b44f0fc-e853-43ff-a547-d4f64dbe7eb7
		summarizeBy: none
		sourceColumn: Indicator

		annotation SummarizationSetBy = Automatic

	partition Fact_UN_Population_Indicators = m
		mode: import
		source =
				let
				    Url =
				        "https://population.un.org/dataportalapi/api/v1/data/indicators/49,19,70,85/locations/208,156,826/start/1990/end/2050" &
				        "?format=csv",
				
				    Source =
				        Csv.Document(Web.Contents(Url, [Timeout=#duration(0, 0, 5, 0), Headers=[Authorization="Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtY2ZhbGwuZGF2aWQyN0Bob3RtYWlsLmNvbSIsImVtYWlsIjoibWNmYWxsLmRhdmlkMjdAaG90bWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6Im1jZmFsbC5kYXZpZDI3QGhvdG1haWwuY29tIiwibmJmIjoxNzcwMzkzOTk5LCJleHAiOjE4MDE5Mjk5OTksImlhdCI6MTc3MDM5Mzk5OSwiaXNzIjoiZG90bmV0LXVzZXItand0cyIsImF1ZCI6ImRhdGEtcG9ydGFsLWFwaSJ9.kF1H5muq9k3yQ0vkYJxirkaJPTFSBXZPIAltpEA6ZcA", Accept="text/csv"]]),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Removed Top Rows" = Table.Skip(Source,1),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Top Rows", "Column1", Splitter.SplitTextByDelimiter("|", QuoteStyle.Csv), {"Column1.1", "Column1.2", "Column1.3", "Column1.4", "Column1.5", "Column1.6", "Column1.7", "Column1.8", "Column1.9", "Column1.10", "Column1.11", "Column1.12", "Column1.13", "Column1.14", "Column1.15", "Column1.16", "Column1.17", "Column1.18", "Column1.19", "Column1.20", "Column1.21", "Column1.22", "Column1.23", "Column1.24", "Column1.25", "Column1.26", "Column1.27", "Column1.28", "Column1.29", "Column1.30", "Column1.31", "Column1.32"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Column1.1", type text}, {"Column1.2", type text}, {"Column1.3", type text}, {"Column1.4", type text}, {"Column1.5", type text}, {"Column1.6", type text}, {"Column1.7", type text}, {"Column1.8", type text}, {"Column1.9", type text}, {"Column1.10", type text}, {"Column1.11", type text}, {"Column1.12", type text}, {"Column1.13", type text}, {"Column1.14", type text}, {"Column1.15", type text}, {"Column1.16", type text}, {"Column1.17", type text}, {"Column1.18", type text}, {"Column1.19", type text}, {"Column1.20", type text}, {"Column1.21", type text}, {"Column1.22", type text}, {"Column1.23", type text}, {"Column1.24", type text}, {"Column1.25", type text}, {"Column1.26", type text}, {"Column1.27", type text}, {"Column1.28", type text}, {"Column1.29", type text}, {"Column1.30", type text}, {"Column1.31", type text}, {"Column1.32", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"LocationId", Int64.Type}, {"Location", type text}, {"Iso3", type text}, {"Iso2", type text}, {"LocationTypeId", Int64.Type}, {"IndicatorId", Int64.Type}, {"Indicator", type text}, {"IndicatorDisplayName", type text}, {"SourceId", Int64.Type}, {"Source", type text}, {"Revision", Int64.Type}, {"VariantId", Int64.Type}, {"Variant", type text}, {"VariantShortName", type text}, {"VariantLabel", type text}, {"TimeId", Int64.Type}, {"TimeLabel", Int64.Type}, {"TimeMid", type number}, {"CategoryId", Int64.Type}, {"Category", type text}, {"EstimateTypeId", Int64.Type}, {"EstimateType", type text}, {"EstimateMethodId", Int64.Type}, {"EstimateMethod", type text}, {"SexId", Int64.Type}, {"Sex", type text}, {"AgeId", Int64.Type}, {"AgeLabel", type text}, {"AgeStart", Int64.Type}, {"AgeEnd", Int64.Type}, {"AgeMid", Int64.Type}, {"Value", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type1",{"IndicatorId", "Indicator"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"IndicatorId"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

