table FACT_Clean_WaterAccess
	lineageTag: 270891b9-11df-407f-93b5-33b5fce4eeca

	column 'Country or Area'
		dataType: string
		lineageTag: 6802c084-cb92-4bfa-a33b-55d98a06b9d6
		summarizeBy: none
		sourceColumn: Country or Area

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: db8ba4c3-650a-4191-9e7c-4367db2902ac
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: d4ee3cbb-c29d-423c-ba41-be33b516217c
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 9dd4a98c-fd7d-40a3-bef1-8c376781476c
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition FACT_Clean_WaterAccess = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Mcfal\OneDrive\Documents\Power BI Desktop\UN_Population_Data\Proportion of population with sustainable access to an improved water source.csv"),[Delimiter=",", Columns=1, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Column1", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Column1.1", "Column1.2", "Column1.3", "Column1.4", "Column1.5", "Column1.6", "Column1.7", "Column1.8"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Column1.1", type text}, {"Column1.2", type text}, {"Column1.3", type text}, {"Column1.4", type text}, {"Column1.5", type text}, {"Column1.6", type text}, {"Column1.7", type text}, {"Column1.8", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type1", [PromoteAllScalars=true]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Promoted Headers",{{"Country or Area", type text}, {"Subgroup", type text}, {"Year", Int64.Type}, {"Source", type text}, {"Unit", type text}, {"Value", Int64.Type}, {"Value Footnotes", Int64.Type}, {"Value Footnotes;;;;;;;;;;;;;;Proportion of population with sustainable access to an improved water source", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type2", each ([Subgroup] = "Total") and ([Country or Area] = "China" or [Country or Area] = "India" or [Country or Area] = "Sub-Saharan Africa" or [Country or Area] = "United States" or [Country or Area] = "World")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"Country or Area", "Year", "Unit", "Value"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

