table Fact_UN_Population_metrics
	lineageTag: 3d76d5a6-3834-480f-a279-ea984c8dbd4d

	measure 'Fertility rate VAR_parallelperiod' =
			
			VAR FerPriorYear =
			    CALCULATE([Fertility Rate M/F], PARALLELPERIOD('Date_table'[Date], -12, MONTH))
			RETURN
			    ([Fertility Rate M/F] - FerPriorYear )
		lineageTag: aa4ba810-34b2-42d1-8aad-f7c745e9d38f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Population M/F' = calculate(sum(Fact_UN_Population_metrics[Total population by sex]),Fact_UN_Population_metrics[Sex]="Both sexes")
		lineageTag: 7b10f16d-945d-4f38-9248-0e8fa568cc06

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Population M/F Ages' = calculate(sum(Fact_UN_Population_metrics[Population by age and sex - broad age groups]),Fact_UN_Population_metrics[Sex]="Both sexes")
		lineageTag: c7525e04-de3a-4d00-a8a3-fb07eedd4750

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fertility Rate M/F' = calculate(sum(Fact_UN_Population_metrics[Total fertility rate]),Fact_UN_Population_metrics[Sex]="Both sexes")
		lineageTag: 55cdc8fe-4f01-4fee-98e9-38a277dc3377

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Potential Support Ratio M/F' = calculate(sum(Fact_UN_Population_metrics[Potential support ratio]),Fact_UN_Population_metrics[Sex]="Both sexes")
		lineageTag: 717e447b-9594-456d-b7ef-a15f8133fdcb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Trend = IF([Fertility rate VAR_parallelperiod] > 0. UNICHAR(9650), UNICHAR(128315))
		lineageTag: b80fde65-90ac-45fa-aebd-ad3bfe26533e

	measure 'Population Latest' =
			
			VAR LatestYear =
			    MAXX(
			        FILTER(
			            ALL(Fact_UN_Population_metrics[EOYear]),
			            CALCULATE(
			                NOT ISBLANK(
			                    SUM(Fact_UN_Population_metrics[Total population by sex])),
			                Fact_UN_Population_metrics[EstimateMethod] = "Interpolation",
			                Fact_UN_Population_metrics[Sex] = "Both sexes")),
			        Fact_UN_Population_metrics[EOYear])
			RETURN
			CALCULATE(
			    SUM(Fact_UN_Population_metrics[Total population by sex]),
			    Fact_UN_Population_metrics[EstimateMethod] = "Interpolation",
			    Fact_UN_Population_metrics[Sex] = "Both sexes",
			    Fact_UN_Population_metrics[EOYear] = LatestYear)
		lineageTag: 5e5b1417-c3a1-4576-aee5-71d75a24b75f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fertility Rate Latest' =
			
			VAR LatestYear =
			    MAXX(
			        FILTER(
			            ALL(Fact_UN_Population_metrics[EOYear]),
			            CALCULATE(
			                NOT ISBLANK(
			                    SUM(Fact_UN_Population_metrics[Total fertility rate])),
			                Fact_UN_Population_metrics[EstimateMethod] = "Interpolation",
			                Fact_UN_Population_metrics[Sex] = "Both sexes")),
			        Fact_UN_Population_metrics[EOYear])
			RETURN
			CALCULATE(
			    SUM(Fact_UN_Population_metrics[Total fertility rate]),
			    Fact_UN_Population_metrics[EstimateMethod] = "Interpolation",
			    Fact_UN_Population_metrics[Sex] = "Both sexes",
			    Fact_UN_Population_metrics[EOYear] = LatestYear)
		lineageTag: 86fd427c-eefa-42a4-abd0-694eb3015a24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PSR (20-64/65+) Latest' =
			
			VAR LatestYear =
			    MAXX(
			        FILTER(
			            ALL(Fact_UN_Population_metrics[EOYear]),
			            CALCULATE(
			                NOT ISBLANK(
			                    SUM(Fact_UN_Population_metrics[Potential support ratio])),
			                Fact_UN_Population_metrics[EstimateMethod] = "Interpolation",
			                Fact_UN_Population_metrics[AgeLabel] = "[20-64/65+]",
			                Fact_UN_Population_metrics[Sex] = "Both sexes")),
			        Fact_UN_Population_metrics[EOYear])
			RETURN
			CALCULATE(
			    SUM(Fact_UN_Population_metrics[Potential support ratio]),
			    Fact_UN_Population_metrics[EstimateMethod] = "Interpolation",
			    Fact_UN_Population_metrics[AgeLabel] = "[20-64/65+]",
			    Fact_UN_Population_metrics[Sex] = "Both sexes",
			    Fact_UN_Population_metrics[EOYear] = LatestYear)
		lineageTag: b6a8eb3a-acc3-480f-aa1e-7384a9b45713

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Potential Support Ratio (20-69/70+) Latest Actual' =
			
			VAR LatestYear =
			    MAXX(
			        FILTER(
			            ALL(Fact_UN_Population_metrics[EOYear]),
			            CALCULATE(
			                NOT ISBLANK(
			                    SUM(Fact_UN_Population_metrics[Potential support ratio])),
			                Fact_UN_Population_metrics[EstimateMethod] = "Interpolation",
			                Fact_UN_Population_metrics[AgeLabel] = "[20-69/50+]",
			                Fact_UN_Population_metrics[Sex] = "Both sexes")),
			        Fact_UN_Population_metrics[EOYear])
			RETURN
			CALCULATE(
			    SUM(Fact_UN_Population_metrics[Potential support ratio]),
			    Fact_UN_Population_metrics[EstimateMethod] = "Interpolation",
			    Fact_UN_Population_metrics[AgeLabel] = "[20-69/70+]",
			    Fact_UN_Population_metrics[Sex] = "Both sexes",
			    Fact_UN_Population_metrics[EOYear] = LatestYear)
		lineageTag: b6a5f5e3-b02b-4049-bff7-0c0de0881605

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Title = CONCATENATE("United Nations Latest Population Data & 2050 Projections: ",SELECTEDVALUE(Fact_UN_Population_metrics[Location], "All Countries Selected"))
		lineageTag: 8cf89d62-2ae5-440a-b98d-27f620233711

	measure LatestDate =
			CALCULATE(
			    MAX(Fact_UN_Population_metrics[EOYear]),
			    REMOVEFILTERS(Fact_UN_Population_metrics[EOYear]))
		formatString: General Date
		lineageTag: cca4ef3f-7efb-4872-abaf-db8e3ba3df64

	measure 'PSR (20-64/65+) Projection' =
			
			VAR LatestYear =
			    MAXX(
			        FILTER(
			            ALL(Fact_UN_Population_metrics[EOYear]),
			            CALCULATE(
			                NOT ISBLANK(
			                    SUM(Fact_UN_Population_metrics[Potential support ratio])),
			                Fact_UN_Population_metrics[EstimateMethod] = "Projection",
			                Fact_UN_Population_metrics[AgeLabel] = "[20-64/65+]",
			                Fact_UN_Population_metrics[Sex] = "Both sexes")),
			        Fact_UN_Population_metrics[EOYear])
			RETURN
			CALCULATE(
			    SUM(Fact_UN_Population_metrics[Potential support ratio]),
			    Fact_UN_Population_metrics[EstimateMethod] = "Projection",
			    Fact_UN_Population_metrics[AgeLabel] = "[20-64/65+]",
			    Fact_UN_Population_metrics[Sex] = "Both sexes",
			    Fact_UN_Population_metrics[EOYear] = LatestYear)
		lineageTag: eb941a83-ffac-4776-8f92-e0ad0ec74a89

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Population Projection' =
			
			VAR LatestYear =
			    MAXX(
			        FILTER(
			            ALL(Fact_UN_Population_metrics[EOYear]),
			            CALCULATE(
			                NOT ISBLANK(
			                    SUM(Fact_UN_Population_metrics[Total population by sex])),
			                Fact_UN_Population_metrics[EstimateMethod] = "Projection",
			                Fact_UN_Population_metrics[Sex] = "Both sexes")),
			        Fact_UN_Population_metrics[EOYear])
			RETURN
			CALCULATE(
			    SUM(Fact_UN_Population_metrics[Total population by sex]),
			    Fact_UN_Population_metrics[EstimateMethod] = "Projection",
			    Fact_UN_Population_metrics[Sex] = "Both sexes",
			    Fact_UN_Population_metrics[EOYear] = LatestYear)
		lineageTag: f8255bff-2b4d-4b81-a478-7f29a5170723

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fertility Rate Projection' =
			
			VAR LatestYear =
			    MAXX(
			        FILTER(
			            ALL(Fact_UN_Population_metrics[EOYear]),
			            CALCULATE(
			                NOT ISBLANK(
			                    SUM(Fact_UN_Population_metrics[Total fertility rate])),
			                Fact_UN_Population_metrics[EstimateMethod] = "Projection",
			                Fact_UN_Population_metrics[Sex] = "Both sexes")),
			        Fact_UN_Population_metrics[EOYear])
			RETURN
			CALCULATE(
			    SUM(Fact_UN_Population_metrics[Total fertility rate]),
			    Fact_UN_Population_metrics[EstimateMethod] = "Projection",
			    Fact_UN_Population_metrics[Sex] = "Both sexes",
			    Fact_UN_Population_metrics[EOYear] = LatestYear)
		lineageTag: 06e0e8b8-23ac-4e18-b85e-bb61a00a6f74

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LocationId
		dataType: int64
		formatString: 0
		lineageTag: 16743b00-86f3-43d6-83b9-b79680b47720
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	column VariantLabel
		dataType: string
		lineageTag: 235dd23d-c261-4298-a668-842840f18d1b
		summarizeBy: none
		sourceColumn: VariantLabel

		annotation SummarizationSetBy = Automatic

	column EstimateMethod
		dataType: string
		lineageTag: f3171321-1323-4992-931f-1b209b0f5b3c
		summarizeBy: none
		sourceColumn: EstimateMethod

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: 16aeee1e-c537-49a7-9045-f8d93290c4a9
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column AgeLabel
		dataType: string
		lineageTag: 32cf14df-6e5e-48f9-a7eb-fc32c8999ac4
		summarizeBy: none
		sourceColumn: AgeLabel

		annotation SummarizationSetBy = Automatic

	column EOYear
		dataType: dateTime
		formatString: Short Date
		lineageTag: 88420bbe-7a4d-4cbe-a572-d392f203af30
		summarizeBy: none
		sourceColumn: EOYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Total fertility rate'
		dataType: double
		lineageTag: e51a218b-98fe-407b-baf5-8f8a003225cc
		summarizeBy: sum
		sourceColumn: Total fertility rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total population by sex'
		dataType: double
		lineageTag: 8cb9ea64-25c6-41fb-8052-ac3a952ddcba
		summarizeBy: sum
		sourceColumn: Total population by sex

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Population by age and sex - broad age groups'
		dataType: double
		lineageTag: 93b145f9-b4b6-4ed2-bbdf-ec0c82d98e01
		summarizeBy: sum
		sourceColumn: Population by age and sex - broad age groups

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Potential support ratio'
		dataType: double
		lineageTag: e9774334-2b4b-4ef3-9b09-cd0eb7ac7bb9
		summarizeBy: sum
		sourceColumn: Potential support ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date Format' = format(Fact_UN_Population_metrics[LatestDate], "mmm yyyy")
		lineageTag: dfbaeb0d-7c93-45aa-a4ea-cac274006a59
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: da2b2db7-6290-4454-aa90-b76f8ee8e544
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	partition Fact_UN_Population_metrics = m
		mode: import
		source =
				let
				    Url =
				        "https://population.un.org/dataportalapi/api/v1/data/indicators/49,19,70,85/locations/156,356,947,1829/start/1970/end/2050" &
				        "?format=csv",
				
				    Source =
				        Csv.Document(Web.Contents(Url, [Timeout=#duration(0, 0, 5, 0), Headers=[Authorization="Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtY2ZhbGwuZGF2aWQyN0Bob3RtYWlsLmNvbSIsImVtYWlsIjoibWNmYWxsLmRhdmlkMjdAaG90bWFpbC5jb20iLCJ1bmlxdWVfbmFtZSI6Im1jZmFsbC5kYXZpZDI3QGhvdG1haWwuY29tIiwibmJmIjoxNzcwMzkzOTk5LCJleHAiOjE4MDE5Mjk5OTksImlhdCI6MTc3MDM5Mzk5OSwiaXNzIjoiZG90bmV0LXVzZXItand0cyIsImF1ZCI6ImRhdGEtcG9ydGFsLWFwaSJ9.kF1H5muq9k3yQ0vkYJxirkaJPTFSBXZPIAltpEA6ZcA", Accept="text/csv"]]),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Removed Top Rows" = Table.Skip(Source,1),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Top Rows", "Column1", Splitter.SplitTextByDelimiter("|", QuoteStyle.Csv), {"Column1.1", "Column1.2", "Column1.3", "Column1.4", "Column1.5", "Column1.6", "Column1.7", "Column1.8", "Column1.9", "Column1.10", "Column1.11", "Column1.12", "Column1.13", "Column1.14", "Column1.15", "Column1.16", "Column1.17", "Column1.18", "Column1.19", "Column1.20", "Column1.21", "Column1.22", "Column1.23", "Column1.24", "Column1.25", "Column1.26", "Column1.27", "Column1.28", "Column1.29", "Column1.30", "Column1.31", "Column1.32"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Column1.1", type text}, {"Column1.2", type text}, {"Column1.3", type text}, {"Column1.4", type text}, {"Column1.5", type text}, {"Column1.6", type text}, {"Column1.7", type text}, {"Column1.8", type text}, {"Column1.9", type text}, {"Column1.10", type text}, {"Column1.11", type text}, {"Column1.12", type text}, {"Column1.13", type text}, {"Column1.14", type text}, {"Column1.15", type text}, {"Column1.16", type text}, {"Column1.17", type text}, {"Column1.18", type text}, {"Column1.19", type text}, {"Column1.20", type text}, {"Column1.21", type text}, {"Column1.22", type text}, {"Column1.23", type text}, {"Column1.24", type text}, {"Column1.25", type text}, {"Column1.26", type text}, {"Column1.27", type text}, {"Column1.28", type text}, {"Column1.29", type text}, {"Column1.30", type text}, {"Column1.31", type text}, {"Column1.32", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"LocationId", Int64.Type}, {"Location", type text}, {"Iso3", type text}, {"Iso2", type text}, {"LocationTypeId", Int64.Type}, {"IndicatorId", Int64.Type}, {"Indicator", type text}, {"IndicatorDisplayName", type text}, {"SourceId", Int64.Type}, {"Source", type text}, {"Revision", Int64.Type}, {"VariantId", Int64.Type}, {"Variant", type text}, {"VariantShortName", type text}, {"VariantLabel", type text}, {"TimeId", Int64.Type}, {"TimeLabel", Int64.Type}, {"TimeMid", type number}, {"CategoryId", Int64.Type}, {"Category", type text}, {"EstimateTypeId", Int64.Type}, {"EstimateType", type text}, {"EstimateMethodId", Int64.Type}, {"EstimateMethod", type text}, {"SexId", Int64.Type}, {"Sex", type text}, {"AgeId", Int64.Type}, {"AgeLabel", type text}, {"AgeStart", Int64.Type}, {"AgeEnd", Int64.Type}, {"AgeMid", Int64.Type}, {"Value", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type1",{"LocationId", "Location", "Indicator", "VariantLabel", "TimeLabel", "EstimateMethod", "Sex", "AgeLabel", "Value"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each ([VariantLabel] = "Median") and ([AgeLabel] = "0-19" or [AgeLabel] = "20-64" or [AgeLabel] = "20-69" or [AgeLabel] = "65+" or [AgeLabel] = "Total" or [AgeLabel] = "[20-64/65+]" or [AgeLabel] = "[20-69/70+]")),
				    #"Pivoted Column" = Table.Pivot(#"Filtered Rows", List.Distinct(#"Filtered Rows"[Indicator]), "Indicator", "Value"),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Pivoted Column",{{"TimeLabel", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type2", "Year", each Date.FromText([TimeLabel])),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "EOYear", each Date.EndOfYear([Year])),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom1",{"Year", "TimeLabel"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Removed Columns",{{"EOYear", type date}})
				in
				    #"Changed Type3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

